name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-Dwarnings'

permissions:
  contents: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref_name == 'main' }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format and Lint
        run: pnpm run check --reporter=github && cargo fmt --check && cargo clippy

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test
