name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: '${{ vars.BITKEY_OSS_APP_ID }}'
          private-key: '${{ secrets.BITKEY_OSS_APP_SECRET }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Git
        run: |
          git config --local user.name "bitkey-oss-bot[bot]"
          git config --local user.email "201862478+bitkey-oss-bot[bot]@users.noreply.github.com"

      - id: changesets
        name: Create release PR or publish to npm
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          setupGitUser: false
    outputs:
      publish: ${{ steps.changesets.outputs.hasChangesets == 'false' }}

  publish:
    name: Publish
    needs: release
    if: ${{ fromJSON(needs.release.outputs.publish) }}
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
